// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculate_jaccard_cpp
double calculate_jaccard_cpp(NumericMatrix mat1, NumericMatrix mat2, double threshold1, double threshold2);
RcppExport SEXP _netify_calculate_jaccard_cpp(SEXP mat1SEXP, SEXP mat2SEXP, SEXP threshold1SEXP, SEXP threshold2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat1(mat1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mat2(mat2SEXP);
    Rcpp::traits::input_parameter< double >::type threshold1(threshold1SEXP);
    Rcpp::traits::input_parameter< double >::type threshold2(threshold2SEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_jaccard_cpp(mat1, mat2, threshold1, threshold2));
    return rcpp_result_gen;
END_RCPP
}
// calculate_hamming_cpp
double calculate_hamming_cpp(NumericMatrix mat1, NumericMatrix mat2, double threshold1, double threshold2);
RcppExport SEXP _netify_calculate_hamming_cpp(SEXP mat1SEXP, SEXP mat2SEXP, SEXP threshold1SEXP, SEXP threshold2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat1(mat1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mat2(mat2SEXP);
    Rcpp::traits::input_parameter< double >::type threshold1(threshold1SEXP);
    Rcpp::traits::input_parameter< double >::type threshold2(threshold2SEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_hamming_cpp(mat1, mat2, threshold1, threshold2));
    return rcpp_result_gen;
END_RCPP
}
// calculate_edge_changes_cpp
List calculate_edge_changes_cpp(NumericMatrix mat1, NumericMatrix mat2, double threshold1, double threshold2);
RcppExport SEXP _netify_calculate_edge_changes_cpp(SEXP mat1SEXP, SEXP mat2SEXP, SEXP threshold1SEXP, SEXP threshold2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat1(mat1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mat2(mat2SEXP);
    Rcpp::traits::input_parameter< double >::type threshold1(threshold1SEXP);
    Rcpp::traits::input_parameter< double >::type threshold2(threshold2SEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_edge_changes_cpp(mat1, mat2, threshold1, threshold2));
    return rcpp_result_gen;
END_RCPP
}
// qap_correlation_cpp
List qap_correlation_cpp(NumericMatrix mat1, NumericMatrix mat2, int n_permutations);
RcppExport SEXP _netify_qap_correlation_cpp(SEXP mat1SEXP, SEXP mat2SEXP, SEXP n_permutationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat1(mat1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mat2(mat2SEXP);
    Rcpp::traits::input_parameter< int >::type n_permutations(n_permutationsSEXP);
    rcpp_result_gen = Rcpp::wrap(qap_correlation_cpp(mat1, mat2, n_permutations));
    return rcpp_result_gen;
END_RCPP
}
// calculate_spectral_distance_cpp
double calculate_spectral_distance_cpp(NumericMatrix mat1, NumericMatrix mat2);
RcppExport SEXP _netify_calculate_spectral_distance_cpp(SEXP mat1SEXP, SEXP mat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat1(mat1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mat2(mat2SEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_spectral_distance_cpp(mat1, mat2));
    return rcpp_result_gen;
END_RCPP
}
// count_duplicate_dyads
int count_duplicate_dyads(CharacterVector actor1, CharacterVector actor2, NumericVector time);
RcppExport SEXP _netify_count_duplicate_dyads(SEXP actor1SEXP, SEXP actor2SEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type actor1(actor1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type actor2(actor2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(count_duplicate_dyads(actor1, actor2, time));
    return rcpp_result_gen;
END_RCPP
}
// count_duplicate_dyads_indexed
int count_duplicate_dyads_indexed(CharacterVector actor1, CharacterVector actor2, NumericVector time);
RcppExport SEXP _netify_count_duplicate_dyads_indexed(SEXP actor1SEXP, SEXP actor2SEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type actor1(actor1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type actor2(actor2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(count_duplicate_dyads_indexed(actor1, actor2, time));
    return rcpp_result_gen;
END_RCPP
}
// get_matrix
NumericMatrix get_matrix(int n_rows, int n_cols, CharacterVector actors_rows, CharacterVector actors_cols, IntegerVector matRowIndices, IntegerVector matColIndices, NumericVector value, bool symmetric, bool missing_to_zero, bool diag_to_NA);
RcppExport SEXP _netify_get_matrix(SEXP n_rowsSEXP, SEXP n_colsSEXP, SEXP actors_rowsSEXP, SEXP actors_colsSEXP, SEXP matRowIndicesSEXP, SEXP matColIndicesSEXP, SEXP valueSEXP, SEXP symmetricSEXP, SEXP missing_to_zeroSEXP, SEXP diag_to_NASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type actors_rows(actors_rowsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type actors_cols(actors_colsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type matRowIndices(matRowIndicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type matColIndices(matColIndicesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type value(valueSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< bool >::type missing_to_zero(missing_to_zeroSEXP);
    Rcpp::traits::input_parameter< bool >::type diag_to_NA(diag_to_NASEXP);
    rcpp_result_gen = Rcpp::wrap(get_matrix(n_rows, n_cols, actors_rows, actors_cols, matRowIndices, matColIndices, value, symmetric, missing_to_zero, diag_to_NA));
    return rcpp_result_gen;
END_RCPP
}
// get_matrix_integer
IntegerMatrix get_matrix_integer(int n_rows, int n_cols, CharacterVector actors_rows, CharacterVector actors_cols, IntegerVector matRowIndices, IntegerVector matColIndices, IntegerVector value, bool symmetric, bool missing_to_zero, bool diag_to_NA);
RcppExport SEXP _netify_get_matrix_integer(SEXP n_rowsSEXP, SEXP n_colsSEXP, SEXP actors_rowsSEXP, SEXP actors_colsSEXP, SEXP matRowIndicesSEXP, SEXP matColIndicesSEXP, SEXP valueSEXP, SEXP symmetricSEXP, SEXP missing_to_zeroSEXP, SEXP diag_to_NASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type actors_rows(actors_rowsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type actors_cols(actors_colsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type matRowIndices(matRowIndicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type matColIndices(matColIndicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type value(valueSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< bool >::type missing_to_zero(missing_to_zeroSEXP);
    Rcpp::traits::input_parameter< bool >::type diag_to_NA(diag_to_NASEXP);
    rcpp_result_gen = Rcpp::wrap(get_matrix_integer(n_rows, n_cols, actors_rows, actors_cols, matRowIndices, matColIndices, value, symmetric, missing_to_zero, diag_to_NA));
    return rcpp_result_gen;
END_RCPP
}
// get_matrix_logical
LogicalMatrix get_matrix_logical(int n_rows, int n_cols, CharacterVector actors_rows, CharacterVector actors_cols, IntegerVector matRowIndices, IntegerVector matColIndices, LogicalVector value, bool symmetric, bool missing_to_zero, bool diag_to_NA);
RcppExport SEXP _netify_get_matrix_logical(SEXP n_rowsSEXP, SEXP n_colsSEXP, SEXP actors_rowsSEXP, SEXP actors_colsSEXP, SEXP matRowIndicesSEXP, SEXP matColIndicesSEXP, SEXP valueSEXP, SEXP symmetricSEXP, SEXP missing_to_zeroSEXP, SEXP diag_to_NASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type actors_rows(actors_rowsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type actors_cols(actors_colsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type matRowIndices(matRowIndicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type matColIndices(matColIndicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type value(valueSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< bool >::type missing_to_zero(missing_to_zeroSEXP);
    Rcpp::traits::input_parameter< bool >::type diag_to_NA(diag_to_NASEXP);
    rcpp_result_gen = Rcpp::wrap(get_matrix_logical(n_rows, n_cols, actors_rows, actors_cols, matRowIndices, matColIndices, value, symmetric, missing_to_zero, diag_to_NA));
    return rcpp_result_gen;
END_RCPP
}
// get_matrix_character
CharacterMatrix get_matrix_character(int n_rows, int n_cols, CharacterVector actors_rows, CharacterVector actors_cols, IntegerVector matRowIndices, IntegerVector matColIndices, CharacterVector value, bool symmetric, bool missing_to_zero, bool diag_to_NA);
RcppExport SEXP _netify_get_matrix_character(SEXP n_rowsSEXP, SEXP n_colsSEXP, SEXP actors_rowsSEXP, SEXP actors_colsSEXP, SEXP matRowIndicesSEXP, SEXP matColIndicesSEXP, SEXP valueSEXP, SEXP symmetricSEXP, SEXP missing_to_zeroSEXP, SEXP diag_to_NASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type actors_rows(actors_rowsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type actors_cols(actors_colsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type matRowIndices(matRowIndicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type matColIndices(matColIndicesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type value(valueSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< bool >::type missing_to_zero(missing_to_zeroSEXP);
    Rcpp::traits::input_parameter< bool >::type diag_to_NA(diag_to_NASEXP);
    rcpp_result_gen = Rcpp::wrap(get_matrix_character(n_rows, n_cols, actors_rows, actors_cols, matRowIndices, matColIndices, value, symmetric, missing_to_zero, diag_to_NA));
    return rcpp_result_gen;
END_RCPP
}
// get_matrix_batch
List get_matrix_batch(IntegerVector n_rows_vec, IntegerVector n_cols_vec, List actors_rows_list, List actors_cols_list, List matRowIndices_list, List matColIndices_list, List value_list, bool symmetric, bool missing_to_zero, bool diag_to_NA);
RcppExport SEXP _netify_get_matrix_batch(SEXP n_rows_vecSEXP, SEXP n_cols_vecSEXP, SEXP actors_rows_listSEXP, SEXP actors_cols_listSEXP, SEXP matRowIndices_listSEXP, SEXP matColIndices_listSEXP, SEXP value_listSEXP, SEXP symmetricSEXP, SEXP missing_to_zeroSEXP, SEXP diag_to_NASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type n_rows_vec(n_rows_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_cols_vec(n_cols_vecSEXP);
    Rcpp::traits::input_parameter< List >::type actors_rows_list(actors_rows_listSEXP);
    Rcpp::traits::input_parameter< List >::type actors_cols_list(actors_cols_listSEXP);
    Rcpp::traits::input_parameter< List >::type matRowIndices_list(matRowIndices_listSEXP);
    Rcpp::traits::input_parameter< List >::type matColIndices_list(matColIndices_listSEXP);
    Rcpp::traits::input_parameter< List >::type value_list(value_listSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< bool >::type missing_to_zero(missing_to_zeroSEXP);
    Rcpp::traits::input_parameter< bool >::type diag_to_NA(diag_to_NASEXP);
    rcpp_result_gen = Rcpp::wrap(get_matrix_batch(n_rows_vec, n_cols_vec, actors_rows_list, actors_cols_list, matRowIndices_list, matColIndices_list, value_list, symmetric, missing_to_zero, diag_to_NA));
    return rcpp_result_gen;
END_RCPP
}
// melt_matrix_cpp
DataFrame melt_matrix_cpp(NumericMatrix mat, bool remove_diagonal, bool remove_zeros, bool na_rm);
RcppExport SEXP _netify_melt_matrix_cpp(SEXP matSEXP, SEXP remove_diagonalSEXP, SEXP remove_zerosSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< bool >::type remove_diagonal(remove_diagonalSEXP);
    Rcpp::traits::input_parameter< bool >::type remove_zeros(remove_zerosSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(melt_matrix_cpp(mat, remove_diagonal, remove_zeros, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// get_all_actors_cpp
CharacterVector get_all_actors_cpp(List nets_list);
RcppExport SEXP _netify_get_all_actors_cpp(SEXP nets_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nets_list(nets_listSEXP);
    rcpp_result_gen = Rcpp::wrap(get_all_actors_cpp(nets_list));
    return rcpp_result_gen;
END_RCPP
}
// align_matrices_cpp
List align_matrices_cpp(NumericMatrix mat1, NumericMatrix mat2, Nullable<CharacterVector> all_actors_arg);
RcppExport SEXP _netify_align_matrices_cpp(SEXP mat1SEXP, SEXP mat2SEXP, SEXP all_actors_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat1(mat1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mat2(mat2SEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type all_actors_arg(all_actors_argSEXP);
    rcpp_result_gen = Rcpp::wrap(align_matrices_cpp(mat1, mat2, all_actors_arg));
    return rcpp_result_gen;
END_RCPP
}
// batch_align_matrices_cpp
List batch_align_matrices_cpp(List nets_list, Nullable<CharacterVector> all_actors_arg, bool include_diagonal);
RcppExport SEXP _netify_batch_align_matrices_cpp(SEXP nets_listSEXP, SEXP all_actors_argSEXP, SEXP include_diagonalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nets_list(nets_listSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type all_actors_arg(all_actors_argSEXP);
    Rcpp::traits::input_parameter< bool >::type include_diagonal(include_diagonalSEXP);
    rcpp_result_gen = Rcpp::wrap(batch_align_matrices_cpp(nets_list, all_actors_arg, include_diagonal));
    return rcpp_result_gen;
END_RCPP
}
// calculate_similarity_matrix_cpp
NumericMatrix calculate_similarity_matrix_cpp(NumericVector attributes, std::string method);
RcppExport SEXP _netify_calculate_similarity_matrix_cpp(SEXP attributesSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type attributes(attributesSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_similarity_matrix_cpp(attributes, method));
    return rcpp_result_gen;
END_RCPP
}
// correlation_cpp
double correlation_cpp(NumericVector x, NumericVector y);
RcppExport SEXP _netify_correlation_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(correlation_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// calculate_homophily_stats_cpp
List calculate_homophily_stats_cpp(NumericMatrix similarity_matrix, LogicalMatrix net_matrix, bool significance_test, int n_permutations, double alpha);
RcppExport SEXP _netify_calculate_homophily_stats_cpp(SEXP similarity_matrixSEXP, SEXP net_matrixSEXP, SEXP significance_testSEXP, SEXP n_permutationsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type similarity_matrix(similarity_matrixSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type net_matrix(net_matrixSEXP);
    Rcpp::traits::input_parameter< bool >::type significance_test(significance_testSEXP);
    Rcpp::traits::input_parameter< int >::type n_permutations(n_permutationsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_homophily_stats_cpp(similarity_matrix, net_matrix, significance_test, n_permutations, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_netify_calculate_jaccard_cpp", (DL_FUNC) &_netify_calculate_jaccard_cpp, 4},
    {"_netify_calculate_hamming_cpp", (DL_FUNC) &_netify_calculate_hamming_cpp, 4},
    {"_netify_calculate_edge_changes_cpp", (DL_FUNC) &_netify_calculate_edge_changes_cpp, 4},
    {"_netify_qap_correlation_cpp", (DL_FUNC) &_netify_qap_correlation_cpp, 3},
    {"_netify_calculate_spectral_distance_cpp", (DL_FUNC) &_netify_calculate_spectral_distance_cpp, 2},
    {"_netify_count_duplicate_dyads", (DL_FUNC) &_netify_count_duplicate_dyads, 3},
    {"_netify_count_duplicate_dyads_indexed", (DL_FUNC) &_netify_count_duplicate_dyads_indexed, 3},
    {"_netify_get_matrix", (DL_FUNC) &_netify_get_matrix, 10},
    {"_netify_get_matrix_integer", (DL_FUNC) &_netify_get_matrix_integer, 10},
    {"_netify_get_matrix_logical", (DL_FUNC) &_netify_get_matrix_logical, 10},
    {"_netify_get_matrix_character", (DL_FUNC) &_netify_get_matrix_character, 10},
    {"_netify_get_matrix_batch", (DL_FUNC) &_netify_get_matrix_batch, 10},
    {"_netify_melt_matrix_cpp", (DL_FUNC) &_netify_melt_matrix_cpp, 4},
    {"_netify_get_all_actors_cpp", (DL_FUNC) &_netify_get_all_actors_cpp, 1},
    {"_netify_align_matrices_cpp", (DL_FUNC) &_netify_align_matrices_cpp, 3},
    {"_netify_batch_align_matrices_cpp", (DL_FUNC) &_netify_batch_align_matrices_cpp, 3},
    {"_netify_calculate_similarity_matrix_cpp", (DL_FUNC) &_netify_calculate_similarity_matrix_cpp, 2},
    {"_netify_correlation_cpp", (DL_FUNC) &_netify_correlation_cpp, 2},
    {"_netify_calculate_homophily_stats_cpp", (DL_FUNC) &_netify_calculate_homophily_stats_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_netify(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
