// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_matrix
NumericMatrix get_matrix(int n_rows, int n_cols, CharacterVector actors_rows, CharacterVector actors_cols, IntegerVector matRowIndices, IntegerVector matColIndices, NumericVector value, bool symmetric);
RcppExport SEXP _netify_get_matrix(SEXP n_rowsSEXP, SEXP n_colsSEXP, SEXP actors_rowsSEXP, SEXP actors_colsSEXP, SEXP matRowIndicesSEXP, SEXP matColIndicesSEXP, SEXP valueSEXP, SEXP symmetricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type actors_rows(actors_rowsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type actors_cols(actors_colsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type matRowIndices(matRowIndicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type matColIndices(matColIndicesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type value(valueSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    rcpp_result_gen = Rcpp::wrap(get_matrix(n_rows, n_cols, actors_rows, actors_cols, matRowIndices, matColIndices, value, symmetric));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_netify_get_matrix", (DL_FUNC) &_netify_get_matrix, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_netify(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
