# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Determine number of duplicate dyad-time obs
#'
#' @param actor1 character vector for actor1
#' @param actor2 character vector for actor2
#' @param time numeric vector for time
#' @return an integer count of number of duplicate dyads
#' @author Shahryar Minhas
#'
#' @keywords internal
#' @noRd
count_duplicate_dyads <- function(actor1, actor2, time) {
    .Call(`_netify_count_duplicate_dyads`, actor1, actor2, time)
}

#' Alternative implementation for small actor sets
#' Uses integer encoding for actors when possible
#'
#' @param actor1 character vector for actor1
#' @param actor2 character vector for actor2
#' @param time numeric vector for time
#' @return an integer count of number of duplicate dyads
#' @author Shahryar Minhas
#'
#' @keywords internal
#' @noRd
count_duplicate_dyads_indexed <- function(actor1, actor2, time) {
    .Call(`_netify_count_duplicate_dyads_indexed`, actor1, actor2, time)
}

#' This function fills in an adjacency matrix based on actors and data
#'
#' @param n_rows integer specifying number of row actors
#' @param n_cols integer specifying number of column actors
#' @param actors_rows character vector of row actors
#' @param actors_cols character vector of column actors
#' @param matRowIndices numeric vector indicating positions of senders in data
#' @param matColIndices numeric vector indicating positions of receivers in data
#' @param value numeric vector of values to fill in cross-sections of adjacency matrices
#' @param symmetric logical indicating whether ties are symmetric
#' @param missing_to_zero logical indicating whether missing values should be set to zero
#' @param diag_to_NA logical indicating whether diagonal should be set to NA
#' @return an adjacency matrix
#' @author Shahryar Minhas, Ha Eun Choi
#'
#' @keywords internal
#' @noRd
get_matrix <- function(n_rows, n_cols, actors_rows, actors_cols, matRowIndices, matColIndices, value, symmetric, missing_to_zero = TRUE, diag_to_NA = TRUE) {
    .Call(`_netify_get_matrix`, n_rows, n_cols, actors_rows, actors_cols, matRowIndices, matColIndices, value, symmetric, missing_to_zero, diag_to_NA)
}

#' This function fills in an adjacency matrix based on actors and data (INTEGER VERSION)
#'
#' @param n_rows integer specifying number of row actors
#' @param n_cols integer specifying number of column actors
#' @param actors_rows character vector of row actors
#' @param actors_cols character vector of column actors
#' @param matRowIndices numeric vector indicating positions of senders in data
#' @param matColIndices numeric vector indicating positions of receivers in data
#' @param value integer vector of values to fill in cross-sections of adjacency matrices
#' @param symmetric logical indicating whether ties are symmetric
#' @param missing_to_zero logical indicating whether missing values should be set to zero
#' @param diag_to_NA logical indicating whether diagonal should be set to NA
#' @return an integer adjacency matrix
#' @author Shahryar Minhas, Ha Eun Choi
#'
#' @keywords internal
#' @noRd
get_matrix_integer <- function(n_rows, n_cols, actors_rows, actors_cols, matRowIndices, matColIndices, value, symmetric, missing_to_zero = TRUE, diag_to_NA = TRUE) {
    .Call(`_netify_get_matrix_integer`, n_rows, n_cols, actors_rows, actors_cols, matRowIndices, matColIndices, value, symmetric, missing_to_zero, diag_to_NA)
}

#' This function fills in an adjacency matrix based on actors and data (LOGICAL VERSION)
#'
#' @param n_rows integer specifying number of row actors
#' @param n_cols integer specifying number of column actors
#' @param actors_rows character vector of row actors
#' @param actors_cols character vector of column actors
#' @param matRowIndices numeric vector indicating positions of senders in data
#' @param matColIndices numeric vector indicating positions of receivers in data
#' @param value logical vector of values to fill in cross-sections of adjacency matrices
#' @param symmetric logical indicating whether ties are symmetric
#' @param missing_to_zero logical indicating whether missing values should be set to FALSE
#' @param diag_to_NA logical indicating whether diagonal should be set to NA
#' @return a logical adjacency matrix
#' @author Shahryar Minhas, Ha Eun Choi
#'
#' @keywords internal
#' @noRd
get_matrix_logical <- function(n_rows, n_cols, actors_rows, actors_cols, matRowIndices, matColIndices, value, symmetric, missing_to_zero = TRUE, diag_to_NA = TRUE) {
    .Call(`_netify_get_matrix_logical`, n_rows, n_cols, actors_rows, actors_cols, matRowIndices, matColIndices, value, symmetric, missing_to_zero, diag_to_NA)
}

#' This function fills in an adjacency matrix based on actors and data (CHARACTER VERSION)
#'
#' @param n_rows integer specifying number of row actors
#' @param n_cols integer specifying number of column actors
#' @param actors_rows character vector of row actors
#' @param actors_cols character vector of column actors
#' @param matRowIndices numeric vector indicating positions of senders in data
#' @param matColIndices numeric vector indicating positions of receivers in data
#' @param value character vector of values to fill in cross-sections of adjacency matrices
#' @param symmetric logical indicating whether ties are symmetric
#' @param missing_to_zero logical indicating whether missing values should be set to empty string
#' @param diag_to_NA logical indicating whether diagonal should be set to NA
#' @return a character adjacency matrix
#' @author Shahryar Minhas, Ha Eun Choi
#'
#' @keywords internal
#' @noRd
get_matrix_character <- function(n_rows, n_cols, actors_rows, actors_cols, matRowIndices, matColIndices, value, symmetric, missing_to_zero = TRUE, diag_to_NA = TRUE) {
    .Call(`_netify_get_matrix_character`, n_rows, n_cols, actors_rows, actors_cols, matRowIndices, matColIndices, value, symmetric, missing_to_zero, diag_to_NA)
}

#' Batch processing version for multiple time periods
#' 
#' @param n_rows_vec integer vector of number of rows for each matrix
#' @param n_cols_vec integer vector of number of columns for each matrix
#' @param actors_rows_list list of character vectors for row actors
#' @param actors_cols_list list of character vectors for column actors  
#' @param matRowIndices_list list of integer vectors for row indices
#' @param matColIndices_list list of integer vectors for column indices
#' @param value_list list of numeric vectors for values
#' @param symmetric logical indicating whether ties are symmetric
#' @param missing_to_zero logical indicating whether missing values should be set to zero
#' @param diag_to_NA logical indicating whether diagonal should be set to NA
#' @return a list of adjacency matrices
#' @author Shahryar Minhas, Ha Eun Choi
#'
#' @keywords internal
#' @noRd
get_matrix_batch <- function(n_rows_vec, n_cols_vec, actors_rows_list, actors_cols_list, matRowIndices_list, matColIndices_list, value_list, symmetric, missing_to_zero = TRUE, diag_to_NA = TRUE) {
    .Call(`_netify_get_matrix_batch`, n_rows_vec, n_cols_vec, actors_rows_list, actors_cols_list, matRowIndices_list, matColIndices_list, value_list, symmetric, missing_to_zero, diag_to_NA)
}

#' Calculate similarity matrix between node attributes
#'
#' @param attributes numeric vector of node attributes
#' @param method character string specifying similarity metric ("correlation", "euclidean", "categorical", "cosine", "jaccard", "manhattan", "hamming")
#' @return numeric matrix of pairwise similarities
#' @author Shahryar Minhas
#'
#' @keywords internal
#' @noRd
calculate_similarity_matrix_cpp <- function(attributes, method) {
    .Call(`_netify_calculate_similarity_matrix_cpp`, attributes, method)
}

#' Correlation calcs for homophily analysis
#'
#' @param x numeric vector of similarities
#' @param y numeric vector of ties (0/1)
#' @return correlation coefficient
#' @author Shahryar Minhas
#'
#' @keywords internal
#' @noRd
correlation_cpp <- function(x, y) {
    .Call(`_netify_correlation_cpp`, x, y)
}

#' Calculate homophily statistics with significance testing
#'
#' @param similarity_matrix numeric matrix of pairwise node similarities
#' @param net_matrix logical matrix of network ties
#' @param significance_test logical whether to perform permutation test
#' @param n_permutations integer number of permutations
#' @param alpha numeric significance level for confidence intervals
#' @return list containing homophily statistics
#' @author Shahryar Minhas
#'
#' @keywords internal
#' @noRd
calculate_homophily_stats_cpp <- function(similarity_matrix, net_matrix, significance_test, n_permutations, alpha) {
    .Call(`_netify_calculate_homophily_stats_cpp`, similarity_matrix, net_matrix, significance_test, n_permutations, alpha)
}

